constitution = {
    "Article2": "Admission or establishment of new States.",
    "Article3": "Formation of new States and alteration of areas, boundaries or names of existing States.",
    "Article5": "Citizenship at the commencement of the Constitution.",
    "Article10": "Continuance of the rights of citizenship.",
    "Article11": "Parliament to regulate the right of citizenship by law.",
    "Article12": "Definition (Fundamental Rights).",
    "Article13": "Laws inconsistent with or in derogation of the fundamental rights.",
    "Article14": "Equality before law.",
    "Article15": "Prohibition of discrimination on grounds of religion, race, caste, sex or place of birth.",
    "Article16": "Equality of opportunity in matters of public employment.",
    "Article19": "Protection of certain rights regarding freedom of speech, etc.",
    "Article20": "Protection in respect of conviction for offences.",
    "Article21": "Protection of life and personal liberty.",
    "Article23": "Prohibition of traffic in human beings and forced labour.",
    "Article24": "Prohibition of employment of children in factories, etc.",
    "Article25": "Right to Freedom of Religion.",
    "Article26": "Management of religious affairs.",
    "Article27": "Freedom as to payment of taxes for promotion of any particular religion.",
    "Article28": "Freedom as to attendance at religious instruction or religious worship in certain educational institutions.",
    "Article29": "Protection of interests of minorities.",
    "Article30": "Right of minorities to establish and administer educational institutions.",
    "Article32": "Remedies for enforcement of rights conferred by this Part.",
    "Article36": "Directive Principles of State Policy.",
    "Article51A": "Fundamental duties.",
    "Article52": "The President of India.",
    "Article58": "Qualifications for election as President.",
    "Article61": "Procedure for impeachment of the President.",
    "Article73": "Extent of executive power of the Union.",
    "Article74": "Council of Ministers to aid and advise President.",
    "Article76": "Attorney-General for India.",
    "Article85": "Sessions of Parliament, prorogation and dissolution.",
    "Article101": "Vacation of seats.",
    "Article102": "Disqualifications for membership.",
    "Article105": "Powers, privileges, etc., of the Houses of Parliament and of the members and committees thereof.",
    "Article110": "Definition of 'Money Bills'.",
    "Article117": "Special provisions as to financial Bills.",
    "Article123": "Power of President to promulgate Ordinances during recess of Parliament.",
    "Article124": "Establishment and constitution of Supreme Court.",
    "Article129": "Supreme Court to be a court of record.",
    "Article130": "Seat of Supreme Court.",
    "Article131": "Original jurisdiction of the Supreme Court.",
    "Article132": "Appellate jurisdiction of Supreme Court in appeals from High Courts in certain cases.",
    "Article133": "Appellate jurisdiction of Supreme Court in appeals from High Courts in regard to civil matters.",
    "Article134": "Appellate jurisdiction of Supreme Court in regard to criminal matters.",
    "Article134A": "Certificate for appeal to the Supreme Court.",
    "Article135": "Jurisdiction and powers of the Federal Court under existing law to be exercisable by the Supreme Court.",
    "Article136": "Special leave to appeal by the Supreme Court.",
    "Article137": "Review of judgments or orders by the Supreme Court.",
    "Article138": "Enlargement of the jurisdiction of the Supreme Court.",
    "Article139": "Conferment on the Supreme Court of powers to issue certain writs.",
    "Article139A": "Transfer of certain cases.",
    "Article140": "Ancillary powers of Supreme Court.",
    "Article141": "Law declared by Supreme Court to be binding on all courts.",
    "Article142": "Enforcement of decrees and orders of Supreme Court and orders as to discovery, etc.",
    "Article143": "Power of President to consult Supreme Court.",
    "Article148": "Comptroller and Auditor-General of India.",
    "Article213": "Power of Governor to promulgate Ordinances during recess of Legislature.",
    "Article215": "High Courts to be courts of record.",
    "Article226": "Power of High Courts to issue certain writs.",
    "Article227": "Power of superintendence over all courts by the High Court.",
    "Article245-255": "Legislative relations between the Union and the States.",
    "Article280": "Finance Commission.",
    "Article299": "Contracts.",
    "Article300": "Suits and proceedings.",
    "Article309-312": "",
    "Article320": "Functions of Public Service Commissions.",
    "Article323A": "Administrative tribunals.",
    "Article326": "Elections to the House of the People and to the Legislative Assemblies of States to be on the basis of adult suffrage.",
    "Article352-360": "Emergency Provisions.",
    "Article368": "Power of Parliament to amend the Constitution and procedure therefor."
}
